#
# Troglobyte AppHub:
# author: Michael Gene Brockus
# gmail: <michaelbrockus@gmail.com>
#
name: Host MacOSX CI

#
# We have is configured so that ci_runner_macosx only runs
# when source files, build scripts and this CI files is
# changed, we should not just run CI for all changes.
#
on:
  push:
    paths:
      - ".github/workflows/ci_runner_macosx.yml"
      - "*.py"   # Python source files
  pull_request:
    branches:
      - "main"
      - "next"
    paths:
      - ".github/workflows/ci_runner_macosx.yml"
      - "*.py"   # Python source files

permissions:
  contents: read

#
# We list all the Mac OSX systems in a nice list so the
# DevOps team can manage them.
# 
jobs:
  #
  # Mac OSX latest host system target
  #
  host_macosx_latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Packages
      run: |
           python -m pip install -r requirements.txt
    - name: Scan Troglo Project
      run: |
           flake8 .
    - name: Test Troglo Project
      run: |
           python -m pytest test/run_tests.py
  #
  # Mac OSX 10 host system target
  #
  host_macosx_10:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Packages
      run: |
           python -m pip install -r requirements.txt
    - name: Scan Troglo Project
      run: |
           flake8 .
    - name: Test Troglo Project
      run: |
           python -m pytest test/run_tests.py
  #
  # Mac OSX 11 host system target
  #
  host_macosx_11:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Packages
      run: |
           python -m pip install -r requirements.txt
    - name: Scan Troglo Project
      run: |
           flake8 .
    - name: Test Troglo Project
      run: |
           python -m pytest test/run_tests.py
  #
  # Mac OSX 12 host system target
  #
  host_macosx_12:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Packages
      run: |
           python -m pip install -r requirements.txt
    - name: Scan Troglo Project
      run: |
           flake8 .
    - name: Test Troglo Project
      run: |
           python -m pytest test/run_tests.py
